#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Sat Nov 28 18:17:35 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class panelDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: panelDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.checkbox_1 = wx.CheckBox(self, wx.ID_ANY, "")
        self.okButton = wx.Button(self, wx.ID_OK, "")
        self.cancelButton = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.okPressed, self.okButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: panelDialog.__set_properties
        self.SetTitle("Panel Selection")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: panelDialog.__do_layout
        self.sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        self.grid_sizer_1 = wx.GridSizer(3, 3, 1, 1)
        label_3 = wx.StaticText(self, wx.ID_ANY, "Check which panels are not functioning")
        self.sizer_14.Add(label_3, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        self.grid_sizer_1.Add(self.checkbox_1, 0, 0, 0)
        self.grid_sizer_1.Add((0, 0), 0, 0, 0)
        self.grid_sizer_1.Add((0, 0), 0, 0, 0)
        self.grid_sizer_1.Add((0, 0), 0, 0, 0)
        self.grid_sizer_1.Add((0, 0), 0, 0, 0)
        self.grid_sizer_1.Add((0, 0), 0, 0, 0)
        self.grid_sizer_1.Add((0, 0), 0, 0, 0)
        self.grid_sizer_1.Add((0, 0), 0, 0, 0)
        self.grid_sizer_1.Add((0, 0), 0, 0, 0)
        self.sizer_14.Add(self.grid_sizer_1, 0, wx.ALL | wx.EXPAND, 2)
        sizer_1.Add(self.okButton, 0, wx.ALIGN_BOTTOM | wx.ALL, 2)
        sizer_1.Add(self.cancelButton, 0, wx.ALIGN_BOTTOM | wx.BOTTOM | wx.RIGHT | wx.TOP, 2)
        self.sizer_14.Add(sizer_1, 0, wx.EXPAND, 0)
        self.SetSizer(self.sizer_14)
        self.sizer_14.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def okPressed(self, event):  # wxGlade: panelDialog.<event_handler>
        print("Event handler 'okPressed' not implemented!")
        event.Skip()

# end of class panelDialog

class MyApp(wx.App):
    def OnInit(self):
        self.mainFrame = panelDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.mainFrame)
        self.mainFrame.ShowModal()
        self.mainFrame.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
