#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Sat Nov 28 18:18:05 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class presetDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: presetDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.presetName = wx.TextCtrl(self, wx.ID_ANY, "")
        self.presetOK = wx.Button(self, wx.ID_OK, "")
        self.button_2 = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.presetOKPressed, self.presetOK)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: presetDialog.__set_properties
        self.SetTitle("Save Preset As:")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: presetDialog.__do_layout
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11.Add((20, 20), 0, 0, 0)
        label_5 = wx.StaticText(self, wx.ID_ANY, "Name:")
        sizer_11.Add(label_5, 0, wx.ALIGN_CENTER, 0)
        sizer_11.Add((20, 20), 0, wx.ALL, 0)
        sizer_11.Add(self.presetName, 0, wx.ALIGN_CENTER, 0)
        sizer_11.Add((20, 20), 0, 0, 0)
        sizer_11.Add(self.presetOK, 0, wx.ALIGN_CENTER, 0)
        sizer_11.Add(self.button_2, 0, 0, 0)
        sizer_10.Add(sizer_11, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_10)
        sizer_10.Fit(self)
        self.Layout()
        # end wxGlade

    def presetOKPressed(self, event):  # wxGlade: presetDialog.<event_handler>
        print("Event handler 'presetOKPressed' not implemented!")
        event.Skip()

# end of class presetDialog

class MyApp(wx.App):
    def OnInit(self):
        self.mainFrame = presetDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.mainFrame)
        self.mainFrame.ShowModal()
        self.mainFrame.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
